<a href="https://colab.research.google.com/github/DecioVdA/ProveComm/blob/main/PERSO_XGBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Perso XGBoost

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



rd_seed = 42

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DecioVdA/ProveComm/refs/heads/main/Wholesale%20customers%20data.csv")

In [3]:
df.head()

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [5]:
round(df.describe(),2)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
count,440.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00
mean,1.32,2.54,12000.30,5796.27,7951.28,3071.93,2881.49,1524.87
std,0.47,0.77,12647.33,7380.38,9503.16,4854.67,4767.85,2820.11
min,1.00,1.00,3.00,55.00,3.00,25.00,3.00,3.00
25%,1.00,2.00,3127.75,1533.00,2153.00,742.25,256.75,408.25
50%,1.00,3.00,8504.00,3627.00,4755.50,1526.00,816.50,965.50
75%,2.00,3.00,16933.75,7190.25,10655.75,3554.25,3922.00,1820.25
max,2.00,3.00,112151.00,73498.00,92780.00,60869.00,40827.00,47943.00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB

In [7]:
df.isnull().sum()

Channel             0
Region              0
Fresh               0
Milk                0
Grocery             0
Frozen              0
Detergents_Paper    0
Delicassen          0
dtype: int64

In [8]:
df['Channel'].unique()

array([2, 1])

In [9]:
df['Channel'] = df['Channel'].replace({2:'Retail',1:'Horeca'})

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    object
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(7), object(1)
memory usage: 27.6+ KB

In [11]:
import plotly.express as px

#### Analisi del bilanciamento del dataset

In [15]:
conteggio = df['Channel'].value_counts().to_frame('cont').reset_index()
fig = px.bar(conteggio, x = 'Channel', y = 'cont', color = 'Channel', title = 'AnalisiBilanciamento ')
fig.show()

In [20]:
def istogrammi(x):
  fig = px.histogram(df, x = x, color='Channel', nbins=20, histnorm='percent', title = f'Analisi di {x}', barmode='group')
  fig.show()

def scatole(x):
  fig = px.box(df, x = x, color = 'Channel', title = f'Box plot di {x}')
  fig.show()

categorie = list(set(df.columns)-{'Channel'})

for i in df[categorie]:
  istogrammi(i)
  scatole(i)

#### Matrice di correlazione

In [26]:
figura = px.imshow(df.corr(numeric_only=True),
                   text_auto='.2f',
                   range_color= [-1,1],
                   height=700,
                   width = 700,
                   title = 'Analisi della Correlazione tra le variabili numeriche')
figura.show()